export const categorizedColors = {
  "Whites & Off-Whites": [
    { name: "Chantilly Lace", hex: "#F4F6F3" },
    { name: "White Dove", hex: "#F0EFEA" },
    { name: "Simply White", hex: "#F5F2E9" },
    { name: "Cloud White", hex: "#F2EFE5" },
    { name: "Swiss Coffee", hex: "#EFEBE0" },
    { name: "Decorator's White", hex: "#EAEFEA" },
    { name: "Alabaster", hex: "#EDEAE0" },
    { name: "Snowbound", hex: "#F2F0EB" },
    { name: "Pure White", hex: "#F4F3ED" },
    { name: "Greek Villa", hex: "#F2EFE4" },
    { name: "Atrium White", hex: "#F0E9E1" },
    { name: "Linen White", hex: "#F3E9D6" },
  ],
  Grays: [
    { name: "Revere Pewter", hex: "#CBC5B9" },
    { name: "Edgecomb Gray", hex: "#D6CFC2" },
    { name: "Stonington Gray", hex: "#C8CAC3" },
    { name: "Gray Owl", hex: "#D3D4CC" },
    { name: "Classic Gray", hex: "#DBD9D1" },
    { name: "Agreeable Gray", hex: "#D1C7B8" },
    { name: "Repose Gray", hex: "#C9C4BB" },
    { name: "Mindful Gray", hex: "#B5B4A7" },
    { name: "Chelsea Gray", hex: "#8D8A82" },
    { name: "Kendall Charcoal", hex: "#696961" },
    { name: "Coventry Gray", hex: "#B9BDBA" },
    { name: "Silver Satin", hex: "#DCDAD3" },
  ],
  Blues: [
    { name: "Hale Navy", hex: "#47515B" },
    { name: "Van Deusen Blue", hex: "#576674" },
    { name: "Palladian Blue", hex: "#A5C4C3" },
    { name: "Wythe Blue", hex: "#AEC3BC" },
    { name: "Quiet Moments", hex: "#C5D5DB" },
    { name: "Naval", hex: "#343C48" },
    { name: "Sea Salt", hex: "#CFD8D4" },
    { name: "Rainwashed", hex: "#C2D4CE" },
    { name: "Upward", hex: "#C5D1D7" },
    { name: "Smoky Blue", hex: "#6F838F" },
    { name: "Brittania Blue", hex: "#7E909A" },
    { name: "Water's Edge", hex: "#7D929D" },
  ],
  Greens: [
    { name: "Saybrook Sage", hex: "#A7AC96" },
    { name: "October Mist", hex: "#CBD1BC" },
    { name: "Guilford Green", hex: "#D0D0B7" },
    { name: "Soft Fern", hex: "#CAD3B8" },
    { name: "Hunter Green", hex: "#42503E" },
    { name: "Evergreen Fog", hex: "#8B8C7A" },
    { name: "Clary Sage", hex: "#B5BAA8" },
    { name: "Retreat", hex: "#BEC9B5" },
    { name: "Dried Thyme", hex: "#89886E" },
    { name: "Rosemary", hex: "#7A7F6F" },
    { name: "Caldwell Green", hex: "#747C69" },
    { name: "Narragansett Green", hex: "#56625F" },
  ],
  "Beiges & Taupes": [
    { name: "Manchester Tan", hex: "#D1C1A8" },
    { name: "Shaker Beige", hex: "#D5C8B0" },
    { name: "Pashmina", hex: "#B5A99A" },
    { name: "Lenox Tan", hex: "#C0A683" },
    { name: "Accessible Beige", hex: "#D6C9BC" },
    { name: "Kilim Beige", hex: "#CEB99E" },
    { name: "Balanced Beige", hex: "#C5B8A8" },
    { name: "Tony Taupe", hex: "#A89A89" },
    { name: "Mega Greige", hex: "#B4A89A" },
    { name: "Latte", hex: "#C3AC93" },
    { name: "Stone Hearth", hex: "#AFA595" },
    { name: "Weimaraner", hex: "#A4988C" },
  ],
  "Reds & Pinks": [
    { name: "Caliente", hex: "#AF392F" },
    { name: "Heritage Red", hex: "#A0352F" },
    { name: "First Light", hex: "#F0DCD7" },
    { name: "Rosy Peach", hex: "#F2B8A2" },
    { name: "Fired Brick", hex: "#8B473D" },
    { name: "Poinsettia", hex: "#A73A35" },
    { name: "Romance", hex: "#EBD6D1" },
    { name: "Coral Clay", hex: "#C9917A" },
    { name: "Rave Red", hex: "#B53531" },
    { name: "Dinner Party", hex: "#823833" },
    { name: "Cranberry Cocktail", hex: "#A3393B" },
    { name: "New London Burgundy", hex: "#8E4B4C" },
  ],
  "Yellows & Oranges": [
    { name: "Weston Flax", hex: "#E9D8A7" },
    { name: "Hawthorne Yellow", hex: "#E6C978" },
    { name: "Windham Cream", hex: "#F3E2C0" },
    { name: "Stuart Gold", hex: "#E4B051" },
    { name: "Friendly Yellow", hex: "#F9E9B9" },
    { name: "Navajo White (SW)", hex: "#E8D5B7" },
    { name: "Restrained Gold", hex: "#D0B281" },
    { name: "Gingery", hex: "#D89961" },
    { name: "Cavern Clay", hex: "#B9856A" },
    { name: "Tangerine Dream", hex: "#F59F49" },
    { name: "Pumpkin Spice", hex: "#C67D3E" },
    { name: "Autumn Cover", hex: "#D69752" },
  ],
  Purples: [
    { name: "Amethyst Shadow", hex: "#8A7E89" },
    { name: "Mauve Mist", hex: "#D4C5D1" },
    { name: "Sleepy Hollow", hex: "#7B7785" },
    { name: "Expression", hex: "#9F86A1" },
    { name: "Dark Purple", hex: "#52435B" },
    { name: "Exclusive Plum", hex: "#786D74" },
    { name: "Veiled Violet", hex: "#D3CAD5" },
    { name: "Beguiling Mauve", hex: "#CBAFB4" },
    { name: "Quixotic Plum", hex: "#614E5F" },
    { name: "Soulful", hex: "#A18998" },
    { name: "Victorian Mauve", hex: "#A98A90" },
    { name: "Crocus", hex: "#C2AED1" },
  ],
  "Blacks & Darks": [
    { name: "Black", hex: "#313133" },
    { name: "Soot", hex: "#3F4141" },
    { name: "Graphite", hex: "#505455" },
    { name: "Raccoon Fur", hex: "#464848" },
    { name: "Wrought Iron", hex: "#505151" },
    { name: "Tricorn Black", hex: "#2E2E2C" },
    { name: "Black Magic", hex: "#323232" },
    { name: "Urbane Bronze", hex: "#5A544B" },
    { name: "Inkwell", hex: "#383D43" },
    { name: "Cyberspace", hex: "#464B50" },
    { name: "Onyx", hex: "#393A3C" },
    { name: "Deep Space", hex: "#41444D" },
  ],
};
export const paintColors = Object.values(categorizedColors).flat();
