export const paintColors = [
  // Benjamin Moore Whites & Off-Whites
  { name: "Chantilly Lace", hex: "#F4F6F3" },
  { name: "White Dove", hex: "#F0EFEA" },
  { name: "Simply White", hex: "#F5F2E9" },
  { name: "Cloud White", hex: "#F2EFE5" },
  { name: "Swiss Coffee", hex: "#EFEBE0" },
  { name: "Decorator's White", hex: "#EAEFEA" },
  { name: "Super White", hex: "#F2F3F0" },
  { name: "Atrium White", hex: "#F0E9E1" },
  { name: "Linen White", hex: "#F3E9D6" },
  { name: "Navajo White", hex: "#F3E5C7" },

  // Sherwin-Williams Whites & Off-Whites
  { name: "Alabaster", hex: "#EDEAE0" },
  { name: "Snowbound", hex: "#F2F0EB" },
  { name: "Pure White", hex: "#F4F3ED" },
  { name: "Dover White", hex: "#F2EADD" },
  { name: "Greek Villa", hex: "#F2EFE4" },
  { name: "White Flour", hex: "#F3EDE3" },
  { name: "Extra White", hex: "#F4F5F3" },
  { name: "High Reflective White", hex: "#F6F7F5" },
  { name: "Westhighland White", hex: "#F2EDE4" },
  { name: "Origami White", hex: "#EFEBE5" },

  // Benjamin Moore Grays
  { name: "Revere Pewter", hex: "#CBC5B9" },
  { name: "Edgecomb Gray", hex: "#D6CFC2" },
  { name: "Stonington Gray", hex: "#C8CAC3" },
  { name: "Gray Owl", hex: "#D3D4CC" },
  { name: "Classic Gray", hex: "#DBD9D1" },
  { name: "Balboa Mist", hex: "#D8D4C9" },
  { name: "Coventry Gray", hex: "#B9BDBA" },
  { name: "Chelsea Gray", hex: "#8D8A82" },
  { name: "Kendall Charcoal", hex: "#696961" },
  { name: "Amherst Gray", hex: "#7B7C77" },
  { name: "Metropolitan", hex: "#AFB3B1" },
  { name: "Wickham Gray", hex: "#D0D3CB" },
  { name: "Silver Satin", hex: "#DCDAD3" },
  { name: "Boothbay Gray", hex: "#B2BAB7" },
  { name: "Stormy Monday", hex: "#A4A5A1" },

  // Sherwin-Williams Grays
  { name: "Agreeable Gray", hex: "#D1C7B8" },
  { name: "Repose Gray", hex: "#C9C4BB" },
  { name: "Mindful Gray", hex: "#B5B4A7" },
  { name: "Dorian Gray", hex: "#A5A299" },
  { name: "Gauntlet Gray", hex: "#8A867F" },
  { name: "Peppercorn", hex: "#5C5C5B" },
  { name: "Iron Ore", hex: "#4C4947" },
  { name: "Worldly Gray", hex: "#B9B5A7" },
  { name: "Colonnade Gray", hex: "#C2C1B5" },
  { name: "Silverplate", hex: "#C8C8C1" },
  { name: "Passive", hex: "#D1D2CA" },
  { name: "Light French Gray", hex: "#C4C4C0" },
  { name: "Functional Gray", hex: "#B9B5A9" },
  { name: "Anew Gray", hex: "#C2B9AC" },
  { name: "Online", hex: "#BCC0C1" },

  // Benjamin Moore Beiges & Taupes
  { name: "Manchester Tan", hex: "#D1C1A8" },
  { name: "Shaker Beige", hex: "#D5C8B0" },
  { name: "Grant Beige", hex: "#BFAE99" },
  { name: "Pashmina", hex: "#B5A99A" },
  { name: "Muslin", hex: "#E3D5BE" },
  { name: "Lenox Tan", hex: "#C0A683" },
  { name: "Stone Hearth", hex: "#AFA595" },
  { name: "Alexandria Beige", hex: "#AF9D83" },
  { name: "Smokey Taupe", hex: "#B5A799" },
  { name: "Weimaraner", hex: "#A4988C" },

  // Sherwin-Williams Beiges & Taupes
  { name: "Accessible Beige", hex: "#D6C9BC" },
  { name: "Kilim Beige", hex: "#CEB99E" },
  { name: "Balanced Beige", hex: "#C5B8A8" },
  { name: "Tony Taupe", hex: "#A89A89" },
  { name: "Mega Greige", hex: "#B4A89A" },
  { name: "Sandbar", hex: "#DDCBAF" },
  { name: "Softer Tan", hex: "#E1CBB3" },
  { name: "Macadamia", hex: "#CDB699" },
  { name: "Nomadic Desert", hex: "#BCA68D" },
  { name: "Latte", hex: "#C3AC93" },

  // Benjamin Moore Blues
  { name: "Hale Navy", hex: "#47515B" },
  { name: "Van Deusen Blue", hex: "#576674" },
  { name: "Newburyport Blue", hex: "#4F606E" },
  { name: "Palladian Blue", hex: "#A5C4C3" },
  { name: "Wythe Blue", hex: "#AEC3BC" },
  { name: "Breath of Fresh Air", hex: "#C8DFE0" },
  { name: "Van Cortland Blue", hex: "#A4B5B9" },
  { name: "Brittania Blue", hex: "#7E909A" },
  { name: "Smoke", hex: "#B0BCC0" },
  { name: "Quiet Moments", hex: "#C5D5DB" },
  { name: "Beach Glass", hex: "#B2C1BE" },
  { name: "Solitude", hex: "#D2DDE0" },
  { name: "Water's Edge", hex: "#7D929D" },
  { name: "Gentleman's Gray", hex: "#3A4651" },
  { name: "New York State of Mind", hex: "#5A6B7C" },

  // Sherwin-Williams Blues
  { name: "Naval", hex: "#343C48" },
  { name: "Sea Salt", hex: "#CFD8D4" },
  { name: "Rainwashed", hex: "#C2D4CE" },
  { name: "Upward", hex: "#C5D1D7" },
  { name: "Krypton", hex: "#CAD3D7" },
  { name: "Misty", hex: "#C5D5D9" },
  { name: "Tradewind", hex: "#BCCDD1" },
  { name: "Distance", hex: "#5E6C75" },
  { name: "In the Navy", hex: "#373E46" },
  { name: "Aleutian", hex: "#A7B4BE" },
  { name: "Comfort Gray", hex: "#CFD6CC" },
  { name: "Silver Strand", hex: "#D5D8D0" },
  { name: "Stardew", hex: "#B9C6CA" },
  { name: "Smoky Blue", hex: "#6F838F" },
  { name: "Poolhouse", hex: "#A0B5B6" },

  // Benjamin Moore Greens
  { name: "Saybrook Sage", hex: "#A7AC96" },
  { name: "October Mist", hex: "#CBD1BC" },
  { name: "High Park", hex: "#8A9782" },
  { name: "Cushing Green", hex: "#616A5A" },
  { name: "Guilford Green", hex: "#D0D0B7" },
  { name: "Hollingsworth Green", hex: "#DDE0D0" },
  { name: "Healing Aloe", hex: "#D5E0D5" },
  { name: "Soft Fern", hex: "#CAD3B8" },
  { name: "Louisburg Green", hex: "#979F88" },
  { name: "Tarrytown Green", hex: "#6D7B67" },
  { name: "Caldwell Green", hex: "#747C69" },
  { name: "Jack Pine", hex: "#515B49" },
  { name: "Hunter Green", hex: "#42503E" },
  { name: "Narragansett Green", hex: "#56625F" },
  { name: "Salamander", hex: "#4D5247" },

  // Sherwin-Williams Greens
  { name: "Evergreen Fog", hex: "#8B8C7A" },
  { name: "Clary Sage", hex: "#B5BAA8" },
  { name: "Retreat", hex: "#BEC9B5" },
  { name: "Svelte Sage", hex: "#C2C0A7" },
  { name: "Liveable Green", hex: "#D3D3BF" },
  { name: "Seafoam", hex: "#D3E0D8" },
  { name: "Contented", hex: "#BFC5B2" },
  { name:: "Dried Thyme", hex: "#89886E" },
  { name: "Rosemary", hex: "#7A7F6F" },
  { name: "Pewter Green", hex: "#788075" },
  { name: "Rookwood Dark Green", hex: "#4A524A" },
  { name: "Forestwood", hex: "#53594F" },
  { name: "Riverway", hex: "#6E8184" },
  { name: "Halcyon Green", hex: "#A4B1A8" },
  { name: "Acacia Haze", hex: "#A7B0A5" },

  // Benjamin Moore Yellows & Oranges
  { name: "Weston Flax", hex: "#E9D8A7" },
  { name: "Hawthorne Yellow", hex: "#E6C978" },
  { name: "Windham Cream", hex: "#F3E2C0" },
  { name: "Philadelphia Cream", hex: "#F6E8CB" },
  { name: "Squish-Squash", hex: "#F8C16E" },
  { name: "Stuart Gold", hex: "#E4B051" },
  { name: "Concord Ivory", hex: "#F2D7A5" },
  { name: "Autumn Cover", hex: "#D69752" },
  { name: "Pumpkin Spice", hex: "#C67D3E" },
  { name: "Tangerine Dream", hex: "#F59F49" },

  // Sherwin-Williams Yellows & Oranges
  { name: "Friendly Yellow", hex: "#F9E9B9" },
  { name: "Naples Yellow", hex: "#F9DA9A" },
  { name: "Navajo White (SW)", hex: "#E8D5B7" },
  { name: "Honied White", hex: "#F6E4C4" },
  { name: "Cachet Cream", hex: "#EEDBB4" },
  { name: "Daffodil", hex: "#FDEB6C" },
  { name: "Restrained Gold", hex: "#D0B281" },
  { name: "Mannered Gold", hex: "#CAA870" },
  { name: "Gingery", hex: "#D89961" },
  { name: "Cavern Clay", hex: "#B9856A" },

  // Benjamin Moore Reds & Pinks
  { name: "Caliente", hex: "#AF392F" },
  { name: "Heritage Red", hex: "#A0352F" },
  { name: "Dinner Party", hex: "#823833" },
  { name: "First Light", hex: "#F0DCD7" },
  { name: "Tissue Pink", hex: "#F8E0DB" },
  { name: "Proposal", hex: "#EBD9D8" },
  { name: "Cranberry Cocktail", hex: "#A3393B" },
  { name: "New London Burgundy", hex: "#8E4B4C" },
  { name: "Rosy Peach", hex: "#F2B8A2" },
  { name: "Custis Salmon", hex: "#EAA88C" },

  // Sherwin-Williams Reds & Pinks
  { name: "Red Bay", hex: "#95554A" },
  { name: "Fired Brick", hex: "#8B473D" },
  { name: "Poinsettia", hex: "#A73A35" },
  { name: "Reddish", hex: "#A66A59" },
  { name: "Romance", hex: "#EBD6D1" },
  { name: "Quaint Peche", hex: "#F3D3C1" },
  { name: "Rose Colored", hex: "#EBCFC7" },
  { name: "Coral Clay", hex: "#C9917A" },
  { name: "Bold Brick", hex: "#994C41" },
  { name: "Rave Red", hex: "#B53531" },

  // Benjamin Moore Purples
  { name: "Amethyst Shadow", hex: "#8A7E89" },
  { name: "Mauve Mist", hex: "#D4C5D1" },
  { name: "Sleepy Hollow", hex: "#7B7785" },
  { name: "Kasbah", hex: "#A18DA4" },
  { name: "Victorian Mauve", hex: "#A98A90" },
  { name: "Odessa Pink", hex: "#E3CFCA" },
  { name: "Crocus", hex: "#C2AED1" },
  { name: "Expression", hex: "#9F86A1" },
  { name: "Grape Juice", hex: "#634B68" },
  { name: "Dark Purple", hex: "#52435B" },

  // Sherwin-Williams Purples
  { name: "Exclusive Plum", hex: "#786D74" },
  { name: "Veiled Violet", hex: "#D3CAD5" },
  { name: "Beguiling Mauve", hex: "#CBAFB4" },
  { name: "Quixotic Plum", hex: "#614E5F" },
  { name: "Mature Grape", hex: "#63495B" },
  { name: "Insightful Rose", hex: "#DBC2C5" },
  { name: "Charming", hex: "#E1C8D0" },
  { name: "Soulful", hex: "#A18998" },
  { name: "Plum Dandy", hex: "#836771" },
  { name: "Cabbage Rose", hex: "#D4B0B9" },

  // Benjamin Moore Blacks & Darks
  { name: "Black", hex: "#313133" },
  { name: "Black Satin", hex: "#3A3B3D" },
  { name: "Soot", hex: "#3F4141" },
  { name: "Graphite", hex: "#505455" },
  { name: "Deep Space", hex: "#41444D" },
  { name: "Raccoon Fur", hex: "#464848" },
  { name: "Wrought Iron", hex: "#505151" },
  { name: "French Beret", hex: "#494B4E" },
  { name: "Cheating Heart", hex: "#52575A" },
  { name: "Onyx", hex: "#393A3C" },

  // Sherwin-Williams Blacks & Darks
  { name: "Tricorn Black", hex: "#2E2E2C" },
  { name: "Black Magic", hex: "#323232" },
  { name: "Greenblack", hex: "#484B46" },
  { name: "Urbane Bronze", hex: "#5A544B" },
  { name: "Grizzle Gray", hex: "#6B6A66" },
  { name: "Inkwell", hex: "#383D43" },
  { name: "Cyberspace", hex: "#464B50" },
  { name: "Web Gray", hex: "#777876" },
  { name: "Grays Harbor", hex: "#657074" },
  { name: "Outerspace", hex: "#535C62" }
];